#!/usr/bin/env bash
#Transfers a file from clien-side to server-side
#
#variables
if [ S# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "S4" "S1" "S3@S2":-
fi
